### ISSUE TITLE
JBWAPI 1.5.1 support

### ISSUE THREAD

**Issue by Ravaelles** [MrTate/JBWEB#1]
Hey man! I wanted to use this great package to get a wall-in functionality, but it seems it's not working with JBWAPI 1.5.1. I tried fixing the parts that cause exceptions, but I failed. Stations seem to work fine, but I never managed to return any wall-in, all I managed to do is to hide the exceptions.

Would it be really hard / time-consuming to provide JBWAPI 1.5.1 support? I think it would be really helpful not just for me, but for the community too.

The exception I'm getting is:
```
Exception in thread "main" java.lang.NullPointerException
	at jbweb.Path.createUnitPath(Path.java:129)
	at jbweb.Wall.initialize(Wall.java:649)
	at jbweb.Wall.<init>(Wall.java:40)
	at jbweb.Walls.createWall(Walls.java:118)
	at jbweb.Walls.createTWall(Walls.java:209)
```

**Comment by MrTate** [comment]
Hey, there were still some bugs with the current release that were never ironed out so those would need to be fixed first. 

Feel free to contribute to the package but I haven't been able to work on it for like 6 months and I don't know when I will be able to again soon.

**Comment by dgant** [comment]
@Ravaelles Specifically https://github.com/JavaBWAPI/JBWAPI/issues/72

**Comment by Jcillo507** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!unVooDoo, @alekssze, @DanjiSes, @AlanRvk, @SeshTiliRest, @Wostafa, @idoh, @euphoria108, @sv-pro, @alphafund, @ifthenelse, @fokind, @sy9777m, @acorn421, @JamesPagetButler, @julianauad, @ak2k, @Jesse-Pinkman-443, @laindream, @junaid33
